// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAErcELesSzR-Gd8dNF-Rgq8GML0d-6kL0',
    appId: '1:139804278641:web:3c246993af4d9e0ff600d0',
    messagingSenderId: '139804278641',
    projectId: 'shopify-8a259',
    authDomain: 'shopify-8a259.firebaseapp.com',
    storageBucket: 'shopify-8a259.appspot.com',
    measurementId: 'G-EZCETY8CWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWYQC5aCqo_czRsXwUPuRf2lhplMC-hk8',
    appId: '1:139804278641:android:32d651c9c451bf71f600d0',
    messagingSenderId: '139804278641',
    projectId: 'shopify-8a259',
    storageBucket: 'shopify-8a259.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGtzEvr-wppbkUCYH1Ad7M7Uceh80CqRE',
    appId: '1:139804278641:ios:6b1c7acec316e285f600d0',
    messagingSenderId: '139804278641',
    projectId: 'shopify-8a259',
    storageBucket: 'shopify-8a259.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGtzEvr-wppbkUCYH1Ad7M7Uceh80CqRE',
    appId: '1:139804278641:ios:6b1c7acec316e285f600d0',
    messagingSenderId: '139804278641',
    projectId: 'shopify-8a259',
    storageBucket: 'shopify-8a259.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAErcELesSzR-Gd8dNF-Rgq8GML0d-6kL0',
    appId: '1:139804278641:web:6c182269997380def600d0',
    messagingSenderId: '139804278641',
    projectId: 'shopify-8a259',
    authDomain: 'shopify-8a259.firebaseapp.com',
    storageBucket: 'shopify-8a259.appspot.com',
    measurementId: 'G-9GFHQ2F637',
  );
}
